"""Phase B allow-list bootstrap.

Queries knowledgeC.db for the top-N most-used user-facing apps over the
last `days` days, filtering to bundle IDs that look like real
user-installed apps. Emits a YAML block the user can paste into
`config.yaml` under `per_app.apps`.
"""

from __future__ import annotations

import logging
import sys
from importlib.resources import files
from pathlib import Path

from macos_bridge.apps import bundle_id_to_app_name
from macos_bridge.db import read_only_copy
from macos_bridge.time_utils import start_of_today_mac_absolute_time

logger = logging.getLogger(__name__)

_QUERIES_PKG = "macos_bridge.queries"

_USER_APP_PREFIXES = (
    "com.apple.",
    "com.google.",
    "com.microsoft.",
    "com.tinyspeck.",
    "com.spotify.",
    "com.discordapp",
    "com.figma.",
    "com.slack.",
    "com.adobe.",
    "com.jetbrains.",
    "com.docker.",
    "com.linear-app",
    "com.notion.",
    "org.mozilla.",
    "com.brave.",
    "com.electron.",
    "com.openai.",
    "com.anthropic.",
)

_DENY_SUBSTRINGS = (
    "helper",
    "agent",
    "xpc",
    "daemon",
    ".service",
    "extension",
    "plugin",
    "uiservice",
)

# Apple bundle IDs to drop even though they have the com.apple. prefix
# (system UI components, frameworks, etc.).
_APPLE_BUILTIN_DENY = {
    "com.apple.dock",
    "com.apple.finder",
    "com.apple.WindowManager",
    "com.apple.controlcenter",
    "com.apple.systemuiserver",
    "com.apple.notificationcenterui",
    "com.apple.loginwindow",
    "com.apple.Spotlight",
    "com.apple.coreservices.uiagent",
    "com.apple.UserNotificationCenter",
    "com.apple.AccountPolicyHelper",
}


def _is_user_app(bundle_id: str) -> bool:
    if not bundle_id:
        return False
    if bundle_id in _APPLE_BUILTIN_DENY:
        return False
    lower = bundle_id.lower()
    if any(s in lower for s in _DENY_SUBSTRINGS):
        return False
    return any(lower.startswith(p) for p in _USER_APP_PREFIXES)


def bootstrap_allowlist(
    knowledge_db: Path,
    tmp_dir: Path,
    *,
    top_n: int = 20,
    days: int = 30,
) -> list[tuple[str, int, str]]:
    """Return the top-N user-facing apps by usage minutes over the last `days`.

    Each tuple is `(bundle_id, total_minutes, friendly_name)`.
    """
    since_mat = start_of_today_mac_absolute_time() - days * 86400
    sql = files(_QUERIES_PKG).joinpath("top_apps_30d.sql").read_text()
    with read_only_copy(knowledge_db, tmp_dir) as conn:
        rows = conn.execute(sql, {"since_mat": since_mat}).fetchall()

    user_apps: list[tuple[str, int, str]] = []
    for bundle_id, seconds in rows:
        if not _is_user_app(bundle_id):
            continue
        minutes = int(float(seconds or 0.0) / 60)
        if minutes <= 0:
            continue
        friendly = bundle_id_to_app_name(bundle_id)
        user_apps.append((bundle_id, minutes, friendly))
        if len(user_apps) >= top_n:
            break
    return user_apps


def emit_yaml(apps: list[tuple[str, int, str]], stream=sys.stdout) -> None:
    """Print a YAML block suitable for pasting under `per_app.apps`."""
    print("# Generated by `macos-mqtt-bridge bootstrap-allowlist`.", file=stream)
    print("# Paste under per_app.apps in config.yaml.", file=stream)
    print("per_app:", file=stream)
    print("  apps:", file=stream)
    for bundle_id, minutes, friendly in apps:
        print(f"    - bundle_id: {bundle_id}", file=stream)
        print(f"      friendly_name: {friendly}    # {minutes}m last 30d", file=stream)
